### ISSUE TITLE
Any plan to support more platforms outside Github ? 

### ISSUE THREAD

**Issue by node** [djyde/ossart#2]

**Comment by djyde** [comment]
ref #1

**Comment by djyde** [comment]
It seems that there is no API from another platform. Do you have any ideas?

**Comment by node** [comment]
> It seems that there is no API from another platform. Do you have any ideas?

Like GitLab , used in many orgs internally.  And Gitee ?

**Comment by node** [comment]
> ref #1

Sad ...
